### ISSUE TITLE
Dataset Link Request

### ISSUE THREAD

**Issue by Carco-git** [royorel/FFHQ-Aging-Dataset#11]
Hey,

 I'm very interested in your work. But, I met some troubles when I wanna use your script. Is it possible for you to share your original dataset google drive shared link after prosessing by the script?

It would be very helpful for my research and I will be very grateful for your help!

Best regards

**Comment by royorel** [comment]
Hello @Carco-git 

Unfortunately, we do not host the dataset on any of our servers and cannot redistribute it in order to not violate any of the image licenses. For the same reason, our code is designed to download the images directly from NVIDIA's google drive and not from any of our servers.

**Comment by Carco-git** [comment]
Thanks for your reply, I'm trying another methods instead of downloading.
