### ISSUE TITLE
Let's move hosting to academic torrent?

### ISSUE THREAD

**Issue by leg0m4n** [royorel/FFHQ-Aging-Dataset#18]
Hi there,

Thank you for your work, these labels were really helpful for my research! I was wondering what do you think about moving the dataset to academic torrent(https://academictorrents.com/)? Google drive became practically unusable for storing open datasets, even with your google api script it hits the quota limit after 1k images. I d be happy to seed it if you decide to move it to torrent.

Many thanks,
Richard

**Comment by royorel** [comment]
Hi Richard,

There is a very specific reason we use the original NVIDIA drive storage for this dataset. We don't own the images for this dataset, and we don't want to create duplicates of them or have be responsible for the content in any way or form. If Nvidia chooses to remove an image from the dataset (or the entire dataset) we want it to automatically be reflected here too. We're  aware of the issues it creates for downloading the datasets, but legal issues force us to host the dataset in its current form.

**Comment by leg0m4n** [comment]
Well, it's CCed so it's totally legal, but I just realized, it's already published there: https://academictorrents.com/details/1c1e60f484e911b564de6b4d8b643e19154d5809, sorry for taking time. maybe it's worth mentioning it on main page of your git repo, because your proposed way of downloading is unusable right now, it will take a person to run the same command 70 times manually.

**Comment by royorel** [comment]
It's indeed CC-ed, but the people whose images are in the dataset can change the license of their images, if they do that, hosting their images is not legal anymore...
