### ISSUE TITLE
FAIL to download FFHQ in-the-wild image & request for preprocessed dataset

### ISSUE THREAD

**Issue by xk-huang** [royorel/FFHQ-Aging-Dataset#3]
Hi @royorel, thanks for the amazing dataset and your works!
I encountered a problem with downloading the FFHQ Aging Dataset. As it is hard for me to get access to Google Drive service, I used a proxy server to download the files. Unfortunately, my proxy server always got banned by Google while downloading the "in-the-wild image".
So I'm wondering that would you mind archiving and uploading the preprocessed dataset? Thanks!

**Comment by royorel** [comment]
Hi @xk-huang, what error message did you get when your proxy server got banned?

Unfortunately, due to legal reasons, we will not able to host the images on our own servers.

**Comment by xk-huang** [comment]
Thanks for your reply! 
Here is my error message:
```
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=547239449272-90kes45pshmp0lcvs3k6bfjmj3tjj98r.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code

Authentication successful.
authorized access to google drive API!
Downloading JSON metadata...
\ done processing 1/2 filesTraceback (most recent call last):
  File "download_ffhq_aging.py", line 374, in <module>
    run_cmdline(sys.argv)
  File "download_ffhq_aging.py", line 369, in run_cmdline
    run(**vars(args))
  File "download_ffhq_aging.py", line 333, in run
    download_files([json_spec, license_specs['json']], drive=drive, **download_kwargs)
  File "download_ffhq_aging.py", line 209, in download_files
    raise exc_info[1].with_traceback(exc_info[2])
  File "download_ffhq_aging.py", line 219, in _download_thread
    pydrive_utils.pydrive_download(drive, spec['file_url'], spec['file_path'])
  File "D:\huangxiaoke\FFHQ-Aging-Dataset\pydrive_utils.py", line 40, in pydrive_download
    pydrive_file.GetContentFile(save_path)
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 210,
in GetContentFile
    self.FetchContent(mimetype, remove_bom)
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 43, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 255,
in FetchContent
    self.content = io.BytesIO(self._DownloadFromUrl(download_url))
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 505, in _DownloadFromUrl
    raise ApiRequestError('Cannot download file: %s' % resp)
pydrive.files.ApiRequestError: Cannot download file: {'x-guploader-uploadid': 'ABg5-UzD9N7wgl_godWr4YMx4Qf6To4Q4ML9LsJ0cTa8oIjHw1oFRPJWZPuNjKvBUq_AaOFIvZ0iL6usHXbaYF8uiwEww1pj6A', 'vary': 'Origin, X-Origin', 'content-type': 'application/json; charset=UTF-8', 'date': 'Thu, 08 Oct 2020 03:09:14 GMT', 'expires': 'Thu, 08 Oct 2020 03:09:14 GMT', 'cache-control': 'private, max-age=0', 'content-length': '320', 'server': 'UploadServer', 'alt-svc': 'h3-Q050=":443";
ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'status': '403'}
```
Even the JSON file could not be downloaded.
 I'm planning to download the `in-the-wild-images` first (0.95 TB, so huge!), and then trying to modify the `download_ffhq_aging.py` script.

**Comment by xk-huang** [comment]
Give another try. Now the error message changes:
```
Your browser has been opened to visit:

    https://accounts.google.com/o/oauth2/auth?client_id=547239449272-90kes45pshmp0lcvs3k6bfjmj3tjj98r.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code

Authentication successful.
authorized access to google drive API!
Downloading JSON metadata...
| done processing 2/2 files
Parsing JSON metadata...
Downloading 70001 files...
/ done processing 0/70001 filesTraceback (most recent call last):
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 237,
in FetchMetadata
    .execute(http=self.http)
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\googleapiclient\_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\googleapiclient\http.py", line 907, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/1ySzcqLcrG6bZX6vY4JtMdUkh7NQC5B5A?alt=json returned "User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the
API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=547239449272">

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "download_ffhq_aging.py", line 374, in <module>
    run_cmdline(sys.argv)
  File "download_ffhq_aging.py", line 369, in run_cmdline
    run(**vars(args))
  File "download_ffhq_aging.py", line 348, in run
    download_files(specs, dst_dir, output_size, drive=drive, **download_kwargs)
  File "download_ffhq_aging.py", line 209, in download_files
    raise exc_info[1].with_traceback(exc_info[2])
  File "download_ffhq_aging.py", line 219, in _download_thread
    pydrive_utils.pydrive_download(drive, spec['file_url'], spec['file_path'])
  File "D:\huangxiaoke\FFHQ-Aging-Dataset\pydrive_utils.py", line 40, in pydrive_download
    pydrive_file.GetContentFile(save_path)
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 210,
in GetContentFile
    self.FetchContent(mimetype, remove_bom)
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 42, in _decorated
    self.FetchMetadata()
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 239,
in FetchMetadata
    raise ApiRequestError(error)
pydrive.files.ApiRequestError: <HttpError 403 when requesting https://www.googleapis.com/drive/v2/files/1ySzcqLcrG6bZX6vY4JtMdUkh7NQC5B5A?alt=json returned "User Rate Limit Exceeded. Rate of requests for user exceed configured project quota. You may consider re-evaluating expected per-user traffic to the API and adjust project quota limits accordingly. You may monitor aggregate quota usage and adjust limits in the API Console: https://console.developers.google.com/apis/api/drive.googleapis.com/quotas?project=547239449272">
```
I reduced the `num_threads` in `get_ffhq_aging.bat`, and finally, it worked:
```
python download_ffhq_aging.py --resolution 256 --pydrive --num_threads 8
````
Maybe issue #2 was caused by the same reason that the rate of requests exceeds the quota?

**Comment by royorel** [comment]
Thanks for letting me know!!

The error message in issue #2 is different and looks like it was caused by the machine limits. However, I think the solution is indeed the same. Run the code with `--num_threads` lower than 32

**Comment by wtliao** [comment]
> Thanks for your reply!
> Here is my error message:
> 
> ```
> Your browser has been opened to visit:
> 
>     https://accounts.google.com/o/oauth2/auth?client_id=547239449272-90kes45pshmp0lcvs3k6bfjmj3tjj98r.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code
> 
> Authentication successful.
> authorized access to google drive API!
> Downloading JSON metadata...
> \ done processing 1/2 filesTraceback (most recent call last):
>   File "download_ffhq_aging.py", line 374, in <module>
>     run_cmdline(sys.argv)
>   File "download_ffhq_aging.py", line 369, in run_cmdline
>     run(**vars(args))
>   File "download_ffhq_aging.py", line 333, in run
>     download_files([json_spec, license_specs['json']], drive=drive, **download_kwargs)
>   File "download_ffhq_aging.py", line 209, in download_files
>     raise exc_info[1].with_traceback(exc_info[2])
>   File "download_ffhq_aging.py", line 219, in _download_thread
>     pydrive_utils.pydrive_download(drive, spec['file_url'], spec['file_path'])
>   File "D:\huangxiaoke\FFHQ-Aging-Dataset\pydrive_utils.py", line 40, in pydrive_download
>     pydrive_file.GetContentFile(save_path)
>   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 210,
> in GetContentFile
>     self.FetchContent(mimetype, remove_bom)
>   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 43, in _decorated
>     return decoratee(self, *args, **kwargs)
>   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 255,
> in FetchContent
>     self.content = io.BytesIO(self._DownloadFromUrl(download_url))
>   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\auth.py", line 75, in _decorated
>     return decoratee(self, *args, **kwargs)
>   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 505, in _DownloadFromUrl
>     raise ApiRequestError('Cannot download file: %s' % resp)
> pydrive.files.ApiRequestError: Cannot download file: {'x-guploader-uploadid': 'ABg5-UzD9N7wgl_godWr4YMx4Qf6To4Q4ML9LsJ0cTa8oIjHw1oFRPJWZPuNjKvBUq_AaOFIvZ0iL6usHXbaYF8uiwEww1pj6A', 'vary': 'Origin, X-Origin', 'content-type': 'application/json; charset=UTF-8', 'date': 'Thu, 08 Oct 2020 03:09:14 GMT', 'expires': 'Thu, 08 Oct 2020 03:09:14 GMT', 'cache-control': 'private, max-age=0', 'content-length': '320', 'server': 'UploadServer', 'alt-svc': 'h3-Q050=":443";
> ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'status': '403'}
> ```
> 
> Even the JSON file could not be downloaded.
> I'm planning to download the `in-the-wild-images` first (0.95 TB, so huge!), and then trying to modify the `download_ffhq_aging.py` script.

I have encountered the same problem as you. I am using pydrive without proxy. It seems strange that every day I can only download a limited number of images (sometimes more than 10k images but sometimes around 1k). Then the following error shows. Setting lower `--num_threads` does not solve the issue for me. Have you downloaded the whole dataset?
`Enter verification code: 4/1AY0e-g6EiLmMOwgph2YKumHd45gr1U9HfBHlEpQ_ii5U5xk6EebHcRzt1Q0
Authentication successful.
authorized access to google drive API!
Parsing JSON metadata...
Downloading 70001 files...
\ done processing 54375/70001 filesTraceback (most recent call last):
  File "download_ffhq_aging.py", line 374, in <module>
    run_cmdline(sys.argv)
  File "download_ffhq_aging.py", line 369, in run_cmdline
    run(**vars(args))
  File "download_ffhq_aging.py", line 348, in run
    download_files(specs, dst_dir, output_size, drive=drive, **download_kwargs)
  File "download_ffhq_aging.py", line 209, in download_files
    raise exc_info[1].with_traceback(exc_info[2])
  File "download_ffhq_aging.py", line 219, in _download_thread
    pydrive_utils.pydrive_download(drive, spec['file_url'], spec['file_path'])
  File "/data/scene_understanding/FFHQ-Aging/FFHQ-Aging-Dataset/pydrive_utils.py", line 40, in pydrive_download
    pydrive_file.GetContentFile(save_path)
  File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/files.py", line 210, in GetContentFile
    self.FetchContent(mimetype, remove_bom)
  File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/files.py", line 43, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/files.py", line 255, in FetchContent
    self.content = io.BytesIO(self._DownloadFromUrl(download_url))
  File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/auth.py", line 75, in _decorated
    return decoratee(self, *args, **kwargs)
  File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/files.py", line 505, in _DownloadFromUrl
    raise ApiRequestError('Cannot download file: %s' % resp)
pydrive.files.ApiRequestError: Cannot download file: {'x-guploader-uploadid': 'ABg5-UzC6691-nm8DP4-m536jUwAII5Y5Tz0pZPgkqq5U-PrxApRaIyjx1RiUyYMa022Y_TIgGlLRgwaeBxZhaMOYppbFQXAgw', 'vary': 'Origin, X-Origin', 'content-type': 'application/json; charset=UTF-8', 'date': 'Wed, 02 Dec 2020 11:09:57 GMT', 'expires': 'Wed, 02 Dec 2020 11:09:57 GMT', 'cache-control': 'private, max-age=0', 'content-length': '320', 'server': 'UploadServer', 'alt-svc': 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'status': '403'}`

**Comment by xk-huang** [comment]
> > Thanks for your reply!
> > Here is my error message:
> > ```
> > Your browser has been opened to visit:
> > 
> >     https://accounts.google.com/o/oauth2/auth?client_id=547239449272-90kes45pshmp0lcvs3k6bfjmj3tjj98r.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2F&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive&access_type=offline&response_type=code
> > 
> > Authentication successful.
> > authorized access to google drive API!
> > Downloading JSON metadata...
> > \ done processing 1/2 filesTraceback (most recent call last):
> >   File "download_ffhq_aging.py", line 374, in <module>
> >     run_cmdline(sys.argv)
> >   File "download_ffhq_aging.py", line 369, in run_cmdline
> >     run(**vars(args))
> >   File "download_ffhq_aging.py", line 333, in run
> >     download_files([json_spec, license_specs['json']], drive=drive, **download_kwargs)
> >   File "download_ffhq_aging.py", line 209, in download_files
> >     raise exc_info[1].with_traceback(exc_info[2])
> >   File "download_ffhq_aging.py", line 219, in _download_thread
> >     pydrive_utils.pydrive_download(drive, spec['file_url'], spec['file_path'])
> >   File "D:\huangxiaoke\FFHQ-Aging-Dataset\pydrive_utils.py", line 40, in pydrive_download
> >     pydrive_file.GetContentFile(save_path)
> >   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 210,
> > in GetContentFile
> >     self.FetchContent(mimetype, remove_bom)
> >   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 43, in _decorated
> >     return decoratee(self, *args, **kwargs)
> >   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 255,
> > in FetchContent
> >     self.content = io.BytesIO(self._DownloadFromUrl(download_url))
> >   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\auth.py", line 75, in _decorated
> >     return decoratee(self, *args, **kwargs)
> >   File "C:\Users\huangxiaoke\.conda\envs\pytorch-cs231n\lib\site-packages\pydrive\files.py", line 505, in _DownloadFromUrl
> >     raise ApiRequestError('Cannot download file: %s' % resp)
> > pydrive.files.ApiRequestError: Cannot download file: {'x-guploader-uploadid': 'ABg5-UzD9N7wgl_godWr4YMx4Qf6To4Q4ML9LsJ0cTa8oIjHw1oFRPJWZPuNjKvBUq_AaOFIvZ0iL6usHXbaYF8uiwEww1pj6A', 'vary': 'Origin, X-Origin', 'content-type': 'application/json; charset=UTF-8', 'date': 'Thu, 08 Oct 2020 03:09:14 GMT', 'expires': 'Thu, 08 Oct 2020 03:09:14 GMT', 'cache-control': 'private, max-age=0', 'content-length': '320', 'server': 'UploadServer', 'alt-svc': 'h3-Q050=":443";
> > ma=2592000,h3-29=":443"; ma=2592000,h3-27=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-T050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'status': '403'}
> > ```
> > 
> > 
> > Even the JSON file could not be downloaded.
> > I'm planning to download the `in-the-wild-images` first (0.95 TB, so huge!), and then trying to modify the `download_ffhq_aging.py` script.
> 
> I have encountered the same problem as you. I am using pydrive without proxy. It seems strange that every day I can only download a limited number of images (sometimes more than 10k images but sometimes around 1k). Then the following error shows. Setting lower `--num_threads` does not solve the issue for me. Have you downloaded the whole dataset?
> `Enter verification code: 4/1AY0e-g6EiLmMOwgph2YKumHd45gr1U9HfBHlEpQ_ii5U5xk6EebHcRzt1Q0 Authentication successful. authorized access to google drive API! Parsing JSON metadata... Downloading 70001 files... \ done processing 54375/70001 filesTraceback (most recent call last): File "download_ffhq_aging.py", line 374, in <module> run_cmdline(sys.argv) File "download_ffhq_aging.py", line 369, in run_cmdline run(**vars(args)) File "download_ffhq_aging.py", line 348, in run download_files(specs, dst_dir, output_size, drive=drive, **download_kwargs) File "download_ffhq_aging.py", line 209, in download_files raise exc_info[1].with_traceback(exc_info[2]) File "download_ffhq_aging.py", line 219, in _download_thread pydrive_utils.pydrive_download(drive, spec['file_url'], spec['file_path']) File "/data/scene_understanding/FFHQ-Aging/FFHQ-Aging-Dataset/pydrive_utils.py", line 40, in pydrive_download pydrive_file.GetContentFile(save_path) File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/files.py", line 210, in GetContentFile self.FetchContent(mimetype, remove_bom) File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/files.py", line 43, in _decorated return decoratee(self, *args, **kwargs) File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/files.py", line 255, in FetchContent self.content = io.BytesIO(self._DownloadFromUrl(download_url)) File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/auth.py", line 75, in _decorated return decoratee(self, *args, **kwargs) File "/home/liao/anaconda3/envs/pyt/lib/python3.6/site-packages/pydrive/files.py", line 505, in _DownloadFromUrl raise ApiRequestError('Cannot download file: %s' % resp) pydrive.files.ApiRequestError: Cannot download file: {'x-guploader-uploadid': 'ABg5-UzC6691-nm8DP4-m536jUwAII5Y5Tz0pZPgkqq5U-PrxApRaIyjx1RiUyYMa022Y_TIgGlLRgwaeBxZhaMOYppbFQXAgw', 'vary': 'Origin, X-Origin', 'content-type': 'application/json; charset=UTF-8', 'date': 'Wed, 02 Dec 2020 11:09:57 GMT', 'expires': 'Wed, 02 Dec 2020 11:09:57 GMT', 'cache-control': 'private, max-age=0', 'content-length': '320', 'server': 'UploadServer', 'alt-svc': 'h3-29=":443"; ma=2592000,h3-T051=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'status': '403'}`

This happened to me and it took me nearly half a month to download the whole dataset. It seem that in the morning (GMT+8) the download quota for me recovered.
